# Question 1:

In [2]:
import numpy as np
np.arr=[]
for np.arr in range(2,51,3):
    print(np.arr,end="  ")

2  5  8  11  14  17  20  23  26  29  32  35  38  41  44  47  50  

# Question 2:

In [3]:
import numpy as np
l1=[]
l2=[]
l1=[int(x) for x in input().split()]  #Enter the elements in list1
l2=[int(x) for x in input().split()]  #Enter the elements in list2
print("\n")

print(l1)                           
print(l2) 

a=np.asarray(l1)                      #Converting list1 into array1
print("\n")
print(a)

b=np.asarray(l2)                      #Converting list2 into array2
print(b)

c=np.concatenate((a,b))               #Concatenate array1 and array2
print("\n")
print(c)

np.sort(c)                            #Sort the concatenated array

25 12 9 100 65
10 68 2 100 72


[25, 12, 9, 100, 65]
[10, 68, 2, 100, 72]


[ 25  12   9 100  65]
[ 10  68   2 100  72]


[ 25  12   9 100  65  10  68   2 100  72]


array([  2,   9,  10,  12,  25,  65,  68,  72, 100, 100])

# Question 3:

In [4]:
a=np.array(12)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3,4,5],[7,8,9,10,11]])
d=np.array([[[1,2,3],[4,2,6]],[[3,5,1],[9,7,6]]])

print(a.ndim,a.size)
print(b.ndim,b.size)
print(c.ndim,c.size)
print(d.ndim,d.size)

0 1
1 6
2 10
3 12


# Question 4:

In [5]:
n=int(input())                   # Enter the no. of elements in array
arr=np.arange(n)
print(arr)
print(arr.ndim)
print("\n")

arr2=arr[np.newaxis, : ]         # Converting 1D array into 2D array using numpy.newaxis 
print(arr2)
print(arr2.ndim)
print("\n")

a=np.expand_dims(arr,axis=1)     # Converting 1D array into 2D array using numpy.expand_dims with axis=1
print(a)
print(a.ndim)

6
[0 1 2 3 4 5]
1


[[0 1 2 3 4 5]]
2


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
2


# Question 5:

In [6]:
arr1=(np.arange(1,5).reshape(2,2))
print(arr1)
print("\n")

arr2=(np.arange(6,10).reshape(2,2))
print(arr2)
print("\n")

print(np.vstack([arr1,arr2]))
print("\n")
print(np.hstack([arr1,arr2]))

[[1 2]
 [3 4]]


[[6 7]
 [8 9]]


[[1 2]
 [3 4]
 [6 7]
 [8 9]]


[[1 2 6 7]
 [3 4 8 9]]


# Question 6

In [7]:
arr=[1,2,3,1,4,5,2,1,4,6,1,4]
print(arr)
u,c=np.unique(arr,return_counts=True)     #'u' => unique elements in the array and 'c' => the count of each unique elements.
print(u)
print(c)

[1, 2, 3, 1, 4, 5, 2, 1, 4, 6, 1, 4]
[1 2 3 4 5 6]
[4 2 1 3 1 1]
